### ISSUE TITLE
Stop needlessly using the public microsoft symbol server in tests

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolicator#1004]
The microsoft symbol server is used incidentally in some tests, like https://github.com/getsentry/symbolicator/blob/9fa7f3912652dfc3af3a4b0e46973e619ec22346/crates/symbolicator/src/endpoints/minidump.rs#L114. We should replace these uses with local fixtures to reduce test duration.

**Comment by vaind** [comment]
There are now also tests that fetch source links from HTTP, e.g. `test_dotnet_source_links_in_app`. I think these could be mocked as well.

**Comment by tobias-wilfert** [comment]
As far as I can see we use the `microsoft_symsrv` function at two places:
https://github.com/getsentry/symbolicator/blob/b83f2a4f2a6d799a60f3386502129ca10fe2f167/crates/symbolicator/src/endpoints/minidump.rs#L120
https://github.com/getsentry/symbolicator/blob/b83f2a4f2a6d799a60f3386502129ca10fe2f167/crates/symbolicator/src/endpoints/symbolicate.rs#L181

Looking at the PRs referencing this Arpad made the following point [here](https://github.com/getsentry/symbolicator/pull/1128#issuecomment-1499255501): 

> However these tests explicitly hit these very specific external symbol servers. We also have https://github.com/getsentry/symbolicator/issues/1004 as we hit the microsoft symbol server more than we absolutely need to. In that case we should also keep at least one test around that actually does hit it though.

So I am a bit unsure if we want to replace both or if only one, which one.

**Comment by loewenheim** [comment]
I would say the second one is the better candidate for replacement—it's meant to test something totally unrelated to Microsoft.
