### ISSUE TITLE
Add an automatic temporary deny-list for "bad" external servers

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1015]
Especially when we start scraping SourceMaps from external servers, we want to be able to temporarily block "bad" servers (whatever that means).

The sentry monolith currently stores this in redis. However we would like to avoid that, as we currently have no redis connection at all, and this would pull in another external service we depend on.
Not relying on a shared redis however means that this deny-list is not being shared across all running symbolicators, and is being thrown away on restarts/deploys.

Using a shared `moka::sync` with a defined TTL would do the job.
Questions remain:

- Where we should put this? Should we use the hostname as it is defined in the "outermost" request, or should we correctly follow redirects?
- We would probably return a `DownloadError` for this, but with a hardcoded message probably?
- What does "bad" server mean? How do we define the logic thats decides whether to block a server?
- Do we need to "allowlist" our own known-good servers, so they are not being "accidentally" blocked by this mechanism?
- If this ends up as an in-memory cache, do we want some bounding for it, or have it unbounded and just expire via TTL?
- Can we apply this to "all" the source types? (http: definitely, gcs: maybe yes, s3: probably not?, sentry: intentionally not?)

**Comment by mitsuhiko** [comment]
* A handful of questions here: how would you actually share a moka cache across symbolicators?
* Do we need that data to be shared? Maybe there is even a reason to consider connection status a per-symbolicator kind of issue?
* Bad server is probably something that will evolve over time. Initially it’s probably > n requests did not complete in the allotted time in a minute
* Yes I think we want to override those limits for blessed servers. Not remove entirely though I think.
* I would apply it to all caches. s3/gcs can be over capacity/payment and it will throttle too.

**Comment by mitsuhiko** [comment]
Sounds like a case of hitcounter ;)
