### ISSUE TITLE
Support NixOS Debug Info System

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/symbolicator#103]
I was not aware of this but NixOS has a pretty good solution for shipping dwarf information. The `cache.nixos.org` server has an index for looking up debug information files within NAR archives.

To quote the docs on this:

> ELF binaries have a unique build ID embedded in them, allowing
> separate debug info files to be looked up. For example, here is the
> build ID of a particular build of `libnixexpr.so`:
>
> ```
> $ readelf -a /nix/store/c0srp6xfqyrjrmqhd1pgw6hcrhcghg87-nix-1.12pre5619_346aeee1/lib/libnixexpr.so | grep 'Build ID'
>    Build ID: bde350fa1f1bbde3649bfce3ae143b87683d8bf9
> ```
>
> Given this build ID, `gdb` and `elfutils` will look in
> `/run/dwarffs/.build-id/bd/e350fa1f1bbde3649bfce3ae143b87683d8bf9.debug`
> to obtain the debug info for this binary. `dwarffs` will then look in
> `https://cache.nixos.org/debuginfo/<build-ID>`:
>
> ```
> $ curl https://cache.nixos.org/debuginfo/bde350fa1f1bbde3649bfce3ae143b87683d8bf9
> {"archive":"../nar/0jz52hawk8wida5b2544i484mws9ddkl8jjpjmw6rzrjf83jr5zw.nar.xz","member":"lib/debug/.build-id/bd/e350fa1f1bbde3649bfce3ae143b87683d8bf9.debug"}
> ```
>
> That is, the debug info is contained in the NAR file
`https://cache.nixos.org/nar/0jz52hawk8wida5b2544i484mws9ddkl8jjpjmw6rzrjf83jr5zw.nar.xz`
> (along with the debug info for other binaries from the same
> package). `dwarffs` will unpack all these debug info files to a cache
> (`/var/cache/dwarffs/`) and serve them from there.

While you can't directly address the debug information file from this you can get the path to the NAR archive and you also know where in the archive the debug companion file is. What you can't know unfortunately is where the binary itself is. We know it's *in* the archive but we would have to scan for it.

Supporting this would be interesting but it would likely require us to have another cache of unpacked nix archives so we don't end up unpacking and fetching the same things over and over again.

**Comment by lheckemann** [comment]
https://github.com/zimbatm/nar-serve might be useful/relevant?

**Comment by jernejstrasner** [comment]
This issue is stale. Closing. Please reopen if necessary.
