### ISSUE TITLE
Support S3 compatible storage as shared cache

### ISSUE THREAD

**Issue by secustor** [getsentry/symbolicator#1040]
Currently only GCS is supported as shared cache which makes it, inefficient to run ephemeral instances outside of GCP.     

Proposal: 
Use the [Minio SDK](https://github.com/minio/minio-rs) to enable to connect to S3 compatible storages. That way users can use other Backends too which are supported by Minio.

**Comment by Swatinem** [comment]
What exactly is your use case like? I’m wondering if the shared cache would even make as much sense for situations outside of Sentrys own scale.

**Comment by secustor** [comment]
We are planning to host sentry components in a stateless cluster in which the nodes and therefore symbolicator instances will be possibly recreated multiple times per hour.    
My understanding is that symbolicator instances are downloading the sources from the sentry filestore via the web instances and therefore create significant load on the web instances.    
I would like to prevent that using the shared cache.

**Comment by loewenheim** [comment]
Closing this after discussion. We won't add this ourselves, but we would gladly accept a contribution!
