### ISSUE TITLE
RFC: Use ArtifactBundles / DebugIds in SourceMap processing

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1054]
# Problem Statement

Right now, most of the release files are actually uploaded as one big archive in `ArtifactBundle` / `SourceBundle` format.
It is still possible to upload files individually, and they may be saved inside of Sentry individually, but the idea is to eventually phase out individual files, and only allow bundled uploads at some point.

As I understand it (pls correct me if I’m wrong), the `files` endpoint will return composite file `id`s, which actually refer to a file inside of a bundle instead of an individual file. Downloading that file via the Sentry API is prohibitively expensive, as Sentry will internally download the bundle, open it, parse its manifest and then transfer just that file to Symbolicator. Doing that for multiple files is expensive and we should avoid it.

Orthogonal to `ArtifactBundles`, files and stack traces will in the future increasingly use `DebugId` to uniquely identify sourcemaps.

# Proposal

I would propose the following changes to both the Sentry API as well as the processing flow in Symbolicator to improve upon the current status.

## Sentry API

@kamilogorek added the possibility to filter for file names when querying for release files.

We should extend this API in the following way:
- Add an additional filter for `DebugId`.
- The query result should prefer to return `ArtifactBundle`s instead of individual files. It should make that distinction clear, so that users know which files are individual files, and which ones are to be found in one of the returned artifact bundles.
- When considering `DebugId`, we have a n:m mapping. So one specific `DebugId` can be contained within a number of archives. The endpoint should make sure to filter this down the smallest set of `ArtifactBundle`s that contain all the files that were queried for.
- *Q*: should the endpoint also return a list of `DebugId` / names that are found in each bundle?

## Simplified Lazy Processing flow

Instead of doing the *batched processing flow* described below, it might be simple to understand and reason about if we just lazily fetch files one at a time when then are needed, I imagine this could look like this:

```
fn process_single_frame:
- get minified file, apply "raw" source context: get_file(...)
- get `SourceMapCache` for the frame by `abs_path, Option<DebugId>`: get_sourcemapcache(...)
- symbolicate based one `SourceMapCache`
- apply source context based on `SourceMapCache`
- if no source context available: fall back to fetch source file and apply source context from there: get_file(...)

fn get_file(filename, Option<DebugId>):
- iterate each locally cached `ArtifactBundle` and look for the file if available
- use a local cached version if available
- otherwise, query sentry API for `DebugId` or filename
  - if available: downloaded either `ArtifactBundle` or indvidual file
- if no file on sentry: scrape from the web

fn get_sourcemapcache(filename, Option<DebugId>):
- fetch minified file: get_file(filename, debug_id)
- get the sourcemap reference via metadata associated with the file
- fetch the sourcemap: get_file(sourcemap_filename, debug_id)
- create a cached `SourceMapCache` from both files
```

### Advantages

- This flow is straight forward and simple to understand
- For the best-case, it would do a single (cached) API request, and a single (cached) download for the `ArtifactBundle`

### Disadvantages
- It will potentially do more API requests and file fetches in the non-optimal case, and:
- Has more "latency" (end-to-end wall time) as it does not parallelize file fetching.

Though I believe we do not need to optimize for latency quite as much to make readability suffer in this case.

<details>
<summary><h2>Batched Processing flow</h2></summary>

The processing flow needs to consider `ArtifactBundle`s. I could consider the following flow:

- Iterate over the stack trace, and build a `Set` of `DebugId`s referenced by the stack trace, plus a `Set` of "file stems" as fallback. ("file stem" here means the `name` in `name.js` / `name.js.map`)
- async: Do one API request providing a filter based on the two `Set`s.
- async: Download the returned `ArtifactBundle`s concurrently, as we know that we will use at least one file from it.
- For each referenced (minified) source file, try resolving it from the result of the API request:
  - If it is in the `ArtifactBundle`, use it from there.
  - If it is an individual file, add it to a `Set` of files to download, but keep its metadata (`SourceMap` reference) around.
  - If it is not found in either, add it to a `Set` of files to scrape from the Web.
- async: Download each file from the previous `Set` concurrently.
- Resolve the `SourceMap` reference:
  - If the original file has metadata, use the `DebugId` from its metadata, otherwise the `SourceMap` reference.
  - If no metadata is available, look for a `sourceMappingUrl` comment.
- Resolve the `SourceMap` itself:
  - If the referenced map is in the `ArtifactBundle`, use it from there.
  - If it is an individual file, add it to a `Set` of files to download.
  - If it is in neither, add it to a `Set` of files to scrape from the Web.
- async: Download each referenced `SourceMap` from the previous `Set` concurrently.
- We should now have all the file contents for both the minified source and the `SourceMap`.
- Create a `SourceMapCache` from the artifacts above.
  - The cache key should mention the source where each of them was downloaded from:
  - For files from `ArtifactBundle`s: The `DebugId` (uuid) of the bundle itself, plus the `DebugId` or filename of the file within the bundle.
  - For files fetched individually: The Sentry `id` of the file.
  - For files scraped from the web: The URL where they were fetched from. (possibly with an added timestamp to intentionally cache-bust?)
- Use the `SourceMapCache` to symbolicate.
- Apply source context lines:
  - In the best case `SourceMapCache` already contains them via `sourcesContent`.
  - Otherwise, look for the original source file in the `ArtifactBundle`.
  - If it is included in the set of individual files (because it happened to match a "file stem", add it to a `Set` of files to download.
  - Otherwise, add its "file stem" to a `Set` of files to query Sentry for.
- async: Query the Sentry API for individual files. For each file we wanted to fetch, check:
  - If the file is available as an individual file, add it to a `Set` of files to download.
  - Otherwise add it to a `Set` of files to scrape from the Web. *Q*: Is that even a thing?
- async: Download each of the referenced files from the previous `Set` concurrently.
- Apply the missing source context lines for each of the files fetched in the previous step.

This flow is quite involved. There is a lot of moving pieces. I tried to batch all the async parts together as much as possible to do things concurrently as much as possible.

**Best-case**:

In this scenario, *all* of the files we would ever need are included in a single `ArtifactBundle`, and we have a single async download for it. This download is also cached, so in the best case, we would have completely synchronous code flow.
Resolving `SourceMap` references and contents themselves can be done straight from the `ArtifactBundle`, and the `SourceMapCache` will have a stable `CacheKey` for it as well.
In the best case, both the Sentry API request, as well as the `ArtifactBundle` are available in cache right away.
If not, we do at most 2 async requests, for the API, and to download the single `ArtifactBundle` that contains everything we need.

**Worst-case**:

I would imagine the worst case scenario as the following:

- async: Do an initial Sentry Query.
- We have neither an `ArtifactBundle`, nor an individual file on Sentry, so we have to:
- async: Scrape the minified source from the web.
- Parse the `sourceMappingUrl` from the downloaded file.
- async: Scrape the sourcemap from the web.
- Symbolicate the stack trace, though we assume that we have no `sourceContent`.
- async: Query the Sentry API for the original source files.
- async: Download individual source files from Sentry.
- apply source context from the downloaded files.

</details>

**Comment by loewenheim** [comment]
> Add an additional filter for `DebugId`.

Given the use case described below (filtering by both debug ids and file stems), I assume this is filtering is intended to be disjunctive (anything that matches the debug id _or_ file stem), is that correct?

> The query result should prefer to return ArtifactBundles instead of individual files. It should make that distinction clear, so that users know which files are individual files, and which ones are to be found in one of the returned artifact bundles.

By "prefer", do you mean that it shouldn't offer you the download of a file contained in an archive at all, only the entire archive?

**Comment by Swatinem** [comment]
Yes to both:
- We want anything matching `DebugId`, *or* file stem.
- In the best-case we want to only return a single archive, in case all the files we were looking for are embedded in that one.

**Comment by Swatinem** [comment]
If we have `DebugId`, we will never fall back to searching by filename, and never fall back to scraping from the web.
