### ISSUE TITLE
Rethink "caches are immutable for all eternity"?

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1059]
Whereas the `Err(CacheError)` side of a `CacheEntry` has always had a TTL that caused errors to be retried after a certain time,
The `Ok` side has always had a TTI (time to idle), and it would *never* be invalidated as long as it is in use.

This is a good fit for native debug files, as their debug-ids should guarantee that one debug-id uniquely identifies an immutable file.
Though in reality, we have seen at least one customer issue related to the customer re-using the same debug-id for different files, and constantly overwriting that debug-id in Sentry.
While the above example was either a fault of the customer, or a problem with our fallback-hashing in case of missing ELF build-ids.

Reminder: we hash the first 4k of the `TEXT` section when there is no build-id.
It is certainly possible that the first 4k are the same for different builds. Just imagine that you are linking a fixed static library version with your constantly changing code. If the linker just happens to always put that static library first, and if it is larger than 4k, the first 4k will always be the same for different builds 🤷🏻‍♂️ 

---

Either way, this might become a bigger problem considering SourceMap processing, where we would have to scrape minified files and/or SourceMaps from the web.
Web requests usually have caching-related headers on them, that specificy say that the file is only valid for a certain time frame, after which, a browser will re-fetch a fresh file.
While it is good practice that web builds use unique hashed file names, projects not following that best-practice might just overwrite existing files with each deploy.

For these cases, we would scrape the sourcemap from the web, and reuse it indefinitely as long as it is in use. We would never pick up an overwritten file, and thus process *new* events with *old* sourcemaps.

---

This is already a problem for the web, and for browsers. Client-side caching can already lead to a missmatch between code running in the browser, and code running on the server. It could also lead to the opposite problem. An *old* event comes in, but using a *new* sourcemap.

This kinda makes me think that this is not a problem that can be solved just by looking at files. We would have to at least look at the `release+dist` as well. Maybe it is enough to scope caches (or at the very least, caches for scraped files) to the `release+dist` as well?

**Comment by loewenheim** [comment]
Closing this as not actionable at this point.
