### ISSUE TITLE
Implement new artifact API requests

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1067]
There is currently work in progress to change the Sentry API that provides us with a list of artifact bundles, or individual artifacts.

https://github.com/getsentry/symbolicator/pull/1058 already added code to look up files within artifact bundles, though that code is not yet used as we simply never create any artifact bundle.

## Why is this important

The current API gives us a list of individual files *within* an artifact bundle (which has the same format as a `SourceBundle`).
Requesting individual files as listed by the current API is prohibitively expensive as the Sentry API will have to internall fetch the artifact bundle, parse its manifest, and unzip / stream individual files… for every file that we request.

## How the API should look like

We can/will provide the following information to the API:
- org, project, release?, dist? (from the event that comes in)
- a set of `DebugId`s for files that actually use those
- a set of "file stems" for files that do not use a `DebugId`.

The API should give us a list of files/urls:
- The (ideally smallest) list of artifact bundles that contain the files that we ask for
- A list of individual files that are not contained in artifact bundles, but match the search

The API should give us the "minimal" set of files we need to download to achieve our goal.
In the ideal case, it would only give us a single artifact bundle which contains within *all* the minified source files and source maps that we would need to symbolicate stack traces for an event.

### What are "file stems"

Given the url `~/path/to/file.min.js`, we want to search for the filename without the extension, which is the "file stem".
In the case above, we would look for `file`. The API could then potentially give us both `file.min.js` as well as `file.js.map`.

## Open Questions:

- We should get a `release` and `dist` with each symbolication request. Do we have only one or potentially more artifact bundles for one request?
- Should we also add "file stems" for files that do have a `DebugId`?
- Should we query for *all* the file stems at first, or rather only preload artifact bundles, and then request individual files lazily whenever they are required?

**Comment by loewenheim** [comment]
For reference: computing a minimal set of files to download is an instance of the [set cover problem](https://en.wikipedia.org/wiki/Set_cover_problem).
