### ISSUE TITLE
Implement caching for SourceMaps

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1068]
We need caches (and appropriate keys) for the following files:

- Artifact bundles
- Individual files downloaded either via artifacts or via scraping from the Web
- Converted `SourceMapCache` files

Apart from the different types of files, we also need to take care of using appropriate cache keys

## Artifact Bundles

The artifact bundle format is the same as `SourceBundle`, which are already served by the `"objects"` cache. We should probably reuse this cache, as it already exists, and already gives us the correct format we expect.

Except that `"objects"` can be more than just `SourceBundle`. I believe it is fair to match on the underlying concrete object type, and just raise an `InternalError` in case it is not the expected `SourceBundle` type.

## Individual files

I believe there is no difference between individually downloaded artifacts from sentry, or files scraped from the web.
Possibly https://github.com/getsentry/symbolicator/pull/1057 will fit this use-case.
The code right now seems to work with `ByteView`, so no additional utf-8 validation seems to be necessary, but someone should double-check.

## `SourceMapCache`

These are derived from minified source and sourcemap. A cache already exists for this type, but it is not yet fully hooked up.

# `CacheKey`

There are a few things to consider that are different from the current handling of `CacheKey`, and how it uses `RemoteFile`.

- For files that were used from within artifact bundles, we should use a key such as `"file XXX within artifact bundle YYY"`.
- For files scraped from the web, we need to possibly figure out a solution to https://github.com/getsentry/symbolicator/issues/1059
- The `sourcemap` part of the `SourceMapCache` may be embedded in the `minified` part. We need to cover that case as well.

I’m thinking of maybe even use a content-hash for the cache key there, as that covers pretty much all the use cases above.
- We need at least the minified file anyway to apply the raw source context, therefore we fetch *some* things already anyway.
- We would not really care which artifact bundle the file came from, and what its name within that bundle is.
- By using a content-hash, we can punt on https://github.com/getsentry/symbolicator/issues/1059 for now and solve it in a different layer.
- For `"embedded"` sourcemaps, we can just re-use the content-hash of the minified file.

**Comment by loewenheim** [comment]
> I’m thinking of maybe even use a content-hash for the cache key there, as that covers pretty much all the use cases above.

Is there a reason not to use a content hash in all cases? File size?

**Comment by Swatinem** [comment]
> Is there a reason not to use a content hash in all cases? File size?

Yes pretty much.

I believe for native the reasoning was that you have the objects meta cache (which arguably could include the content hash of the object file itself. within the meta cache file I mean, not as the key to the meta cache), as a shortcut to not have to download the file itself. So you can have a meta cache + symcache without needing the actual object.

For sourcemaps, we would always need at least the minified file anyway.

**Comment by Swatinem** [comment]
There is pretty much these comments that need to be figuring out:

https://github.com/getsentry/symbolicator/blob/e1c755b57f20bef94c8b62e5cd3105c4d7308816/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L392-L395

https://github.com/getsentry/symbolicator/blob/e1c755b57f20bef94c8b62e5cd3105c4d7308816/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L460-L462

https://github.com/getsentry/symbolicator/blob/e1c755b57f20bef94c8b62e5cd3105c4d7308816/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L299-L300

It might also be possible to just use a content-hash for both minified source and sourcemap?
We have to fetch the minified source either way (for raw source context). Though we could potentially skip downloading / extracting the sourcemap itself if we just use its "reference" as the cache key. Then actually downloading the sourcemap itself would happen inside the cache computation.

**Comment by Swatinem** [comment]
Caching based on content hash was implemented in #1079 
Caching for artifact bundles is still open though, as we still don’t have a way to actually fetch those.
