### ISSUE TITLE
Sentry returns empty list when requesting symbols file

### ISSUE THREAD

**Issue by npockrus-bnet** [getsentry/symbolicator#107]
I am running into an issue working with symbolicator where sentry returned an empty list of debug files when symbolicator reached out of the debug files list. The Microsoft files had no issue. Sentry seems to be able to communicate otherwise with symbolicator. 

I set the two config options in Sentry that are documented in the repo (whitelisted symbolicator in sentry and enabled it). I am not using dev services up but instead running symbolicator on another host in the same network. Is there a config I'm missing?

**Comment by npockrus-bnet** [comment]
Follow up: I rebuild from sentry head and it now seems to return values in the list but symbolicator is crashing with the following error:
`2019-08-09T22:55:07Z [actix_net::server::server] INFO: Starting 4 workers
2019-08-09T22:55:07Z [actix_net::server::server] INFO: Starting server on 0.0.0.0:3021
2019-08-09T22:55:07Z [symbolicator::app] INFO: Started http server: 0.0.0.0:3021
2019-08-09T22:55:47Z [symbolicator::actors::symbolication] INFO: Error while fetching cficache: failed to download object
  caused by: failed to fetch data from Sentry
  caused by: failed parsing JSON response from Sentry
  caused by: Json deserialize error: expected value at line 1 column 1
  caused by: expected value at line 1 column 1
`
the json output from the endpoint is: 
`[
{
objectName: "test.pdb",
symbolType: "pdb",
dateCreated: "2019-08-09T19:39:41.744Z",
debugId: "xxxxxxxxxxxxxxxxxxxxx",
data: {
type: "dbg",
features: [
"debug",
"unwind",
"symtab"
]
},
id: "1",
size: 643072,
sha1: "xxxxxxxxxxxxxxxxxxxxx",
uuid: "xxxxxxxxxxxxxxxxxxxxx",
cpuName: "x86",
headers: {
Content-Type: "application/x-ms-pdb"
},
codeId: null
}
]`

I ran it through a json lent process and it also returns that it is invalid json.

**Comment by jan-auer** [comment]
Are you running with a recent `master` build of Sentry? Symbolicator cannot be used with Sentry 9.

**Comment by Swatinem** [comment]
This seems to be related to very old json payloads and may be a version incompatibility.

Please reopen if this is still an issue with the latest versions of both sentry and symbolicator.
