### ISSUE TITLE
Make source context resolution optional

### ISSUE THREAD

**Issue by vaind** [getsentry/symbolicator#1105]
We should make "we want source context" configurable / an input option in symbolicator.
For example the profiling product goes through symbolicator, but does not use source context at all (they throw it away in the profiling processor AFAIK). We could potentially make profiles cheaper to symbolicate by just not doing source context resolution at all. CC @indragiek 

It may also be worth considering making the lines of context configurable, as it is hardcoded to `5` right now.

_Originally posted by @Swatinem in https://github.com/getsentry/rfcs/pull/74#discussion_r1108552113_

**Comment by phacops** [comment]
That would be very much appreciated to have options for that. Not only it's taking more time to symbolicate for us but we do have to loop through the results and discard all contexts to not blow up what we store (and don't display anyway).

**Comment by vaind** [comment]
@phacops can you point out (link to the code) for the profiling-specific symbolication
