### ISSUE TITLE
Support more `data:` URL variants

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#1158]
We currently only match `data:application/json;base64,`, which is a bit restrictive:

https://github.com/getsentry/symbolicator/blob/8c3ee0db76649706b8f3363a030d84b6a9c7763f/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L336

We should support all kinds of `data:` urls, with different mimetypes and non-base64 encoding as well.

**Comment by loewenheim** [comment]
What is the general form of such a preamble?

**Comment by Swatinem** [comment]
Pretty much just `data:`, as the mimetype is optional, and instead of base64 encoding, one can use url-encoding.
