### ISSUE TITLE
Url support for source bundles

### ISSUE THREAD

**Issue by DamGouz** [getsentry/symbolicator#1194]
It would be great if source bundles had support for fetching source files from a url, rather than from a file inside the zip file.
That way, we can fetch sources directly from Perforce by using Swarm urls, even though Perforce is not supported by sentry.

**Comment by DamGouz** [comment]
But what about adding that exact same source-link feature in source bundles, as we don't always have control over the event context.

**Comment by Swatinem** [comment]
I would assume the `SourceBundle` manifest would need to be adapted for that, probably with some non-trivial changes.
Not to mention than you would have to somehow upload such a special `SourceBundle` via sentry-cli somehow…

**Comment by Swatinem** [comment]
As discussed in chat, I believe all the missing pieces here are implemented.

We have put in sourcelink support into the SourceBundle manifest format, however it is currently only aimed at "power users", as it requires manually building a SourceBundle.

Support for authentication was also added, using the same form that we use for JS scraping.
