### ISSUE TITLE
Native frames are ignored for JS events in symbolicli

### ISSUE THREAD

**Issue by jpochyla** [getsentry/symbolicator#1196]
`symbolicli` switches quite soon on the type of the event, and for JS events, all stack frames are processed as JS. So, i.e. WASM/native frames fail to symbolicate and end up as errors in the final report.

**Comment by Swatinem** [comment]
This is the case for `symbolicli`, but also for us now in production as well. Can you share an example event that has a mixed stacktrace so we can properly support this?

**Comment by jpochyla** [comment]
Just curious, would I get better results by inverting the event? -- submitting a `native` one with `javascript` frames? This is directly mentioned in the docs I think.

**Comment by loewenheim** [comment]
In that case all the JS frames would be filtered out before symbolicating.

**Comment by jpochyla** [comment]
Is anybody currently working on this? I can try!

**Comment by loewenheim** [comment]
We are not currently working on it. Contributions are welcome :)

**Comment by Swatinem** [comment]
We just fixed that is `sentry` itself by calling out to Sentry twice, once with all the JS frames, and then with all the Native frames. It should be possible to do two passes on that for symbolicli as well with some effort.
