### ISSUE TITLE
Source maps not applied to event.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/symbolicator#1198]
Due to the possible PII involved in the issue, the information is also available in this internal issue: https://getsentry.atlassian.net/browse/ISSUE-1665

TLDR: Source maps are uploaded to Sentry and applied to the events, but the results are incorrect even when using 3 different tools.

**Comment by loewenheim** [comment]
I took an in-depth look at the second event linked in Jira. What’s happening is that the source and sourcemap file we find during symbolication are not the right ones for the event. For a given release/dist pair, we don’t have precise control over which release bundles we fetch, so if too many bundles are uploaded for the same release/dist pair, that increases the chances that the one we get does not fit the event.

The solution is to either create new releases more often or use debug ids to make the association between events and bundles unambiguous.
