### ISSUE TITLE
Configure IP whitelist instead of boolean flag

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/symbolicator#120]
I don't understand why source connections are blocked to the LAN, see:

https://github.com/getsentry/symbolicator/blob/a886e2e3e14afc514fe40ad111203f0dce06da27/src/utils/http.rs#L14-L21

As discussed in #102, I'm looking at building a small Python adapter to serve symbols into Symbolicator via the HTTP interface. I can hack this list out and rebuild Symbolicator, but I don't understand why it's being blocked in the first place. If nothing else, could weconsider only blocking those addresses when they come in via the multipart symbolication request, and not when they are set in the config yaml?

**Comment by untitaker** [comment]
The boolean setting "connect_to_reserved_ips" disables this blocking. The reason behind this change is that source configuration is part of untrusted user input, and we want to prevent users from making Symbolicator connect to our internal network.

**Comment by mikepurvis** [comment]
Gotcha— should have read a bit more of the file I quoted. :)

Feel free to close the ticket unless you think there's value in the suggestion to only block when the source info is user supplied vs config file defined.

**Comment by mitsuhiko** [comment]
For most deployments disabling it would not be a good idea. We should rather have an explicit whitelist to override this I think.

**Comment by jernejstrasner** [comment]
This issue is stale. Closing. Please reopen if necessary.
