### ISSUE TITLE
Follow source links for not-in-app frames

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/symbolicator#1214]
In .NET, many third party libraries on nuget (and .NET itself) contains source links, which Sentry can use to provide source context.  All the logic is there and works, thanks to @vaind's work on #1103 (and others).  However, we're currently only using it for frames marked with `"in_app": true`.

While I understand we did this to reduce load, we've also defeated the main advantage to having source links at all.  In other words, when frames are truly part of the app - we generally don't need source links because we already have a mechanism for the user to upload source bundles directly to Sentry.  (via `sentry-cli debug-files upload`, which we've automated in the .NET SDK with `<SentryUploadSources>`).

Conversely, third-party and framework sources aren't uploaded - but do have source links.  They are marked `"in_app": false` - as they are considered "System" frames.  Despite often having source links, they're not being followed - and thus we don't get source context for these frames.

Consider:

https://sentry-sdks.sentry.io/issues/4226079286/events/4480bf48ab2a4fb79bc2eb8d9eb65dae/
![image](https://github.com/getsentry/symbolicator/assets/1396388/7fdfdec5-fa10-4192-b7ac-322bbe4b0cbe)

This is typical - source context is visible for the in-app frames, and comes from source bundle upload.  Source context is not visible for library and framework frames.

If I manually force `"in_app": true`, then source links are followed and we see the full source context on all frames:

https://sentry-sdks.sentry.io/issues/4226079286/events/59fc93d9a2e844d780ce8c756683b42e/
![image](https://github.com/getsentry/symbolicator/assets/1396388/5d60b7bb-7c8e-4c14-9f44-0e9271155ffc)

That would be the prefered result for system frames.

While this was [by design](https://github.com/vaind/sentry-rfcs/blob/rfc/source-context-via-links/text/0074-source-context-via-links.md#selected-option---combined-approach), I believe we should reconsider it - as source links provide the most value for system frames, not in-app frames.

This is in code here:
https://github.com/getsentry/symbolicator/blob/0906b233b2282e919e1861096c0b937f50e365a1/crates/symbolicator-service/src/services/symbolication/mod.rs#L195-L196

We might also need to re-think or expand the caching story to reduce load.  Ideally we'd prevent retrieving the same file multiple times.

**Comment by Swatinem** [comment]
Note from triage:

The change to allow this is a fairly simple one-liner.

The more difficult thing is making sure we are correctly caching these things and not overflowing either the cache size, or the number of downloads we do.
Specifically, if a debug file is fetched from a public (shared) symbol server like NuGet, any source links referenced from that one should also be shared among all projects using it.
