### ISSUE TITLE
symsorter performance issue generating source bundles for large PDB's

### ISSUE THREAD

**Issue by donalmacc** [getsentry/symbolicator#1217]
Hey.

We have some large PDB's, a lot of source code, and are investigating using symbolicator+symsorter to handle them. 

We're seeing very long times to generate a source bundle on a large (2GB) pdb file (it's an unreal engine client). 

Running `symsorter -o out--prefix Foo --bundle-id bundle WindowsClient`  takes ~5 seconds to execute (which is great), but running `symsorter -o out  --with-sources  --prefix Foo --bundle-id bundle WindowsClient`  (i.e. just adding ` --with-sources`) takes 10 minutes.

**Comment by Swatinem** [comment]
Even 5 seconds is unreasonable. Have you built it yourself, maybe missing the `--release`?

Otherwise, this indeed walks through all of the debug info in the file, reads all the files referenced, and zips them into an archive. But 10 minutes is completely unreasonable for that.

**Comment by donalmacc** [comment]
5 seconds is acceptable for us when our CI takes longer than that to accept a job 😎 

I've built myself, with `cargo build --release`, and ran the above. The repro was on windows, and I'm not sure how to generate a flamegraph on Rust, but I can try generating a flamegraph of the process tomorrow and share it here.

**Comment by donalmacc** [comment]
Hey. So, turns out flamegraph works just fine on windows! I've confirmed I've built latest with `cargo build --release`, and then ran with:
`flamegraph -- D:/Source/symbolicator/target/release/symsorter.exe -o folder --ignore-errors --prefix foo--bundle-id bundle WindowsClient`
and 
`flamegraph -- D:/Source/symbolicator/target/release/symsorter.exe -o folder --with-sources --ignore-errors --prefix foo--bundle-id bundle WindowsClient`


WIthout sources takes ~  5 seconds 
![no_sources](https://github.com/getsentry/symbolicator/assets/861243/c51d97b9-e243-411c-a8c4-ae34d5204491)


With sources takes ~ 10 minutes 
![with_sources](https://github.com/getsentry/symbolicator/assets/861243/b664bcf5-e596-49d5-ab33-d77ee71a3d4c)

**Comment by Swatinem** [comment]
Thanks for the analysis.

According to the flamegraph, the runtime is dominated by zip compression. What kind of debug files are you processing there? And what kind of sources are they referencing? Do the final source bundles end up unreasonably large?

**Comment by donalmacc** [comment]
It's a single PDB file generated by VS2019, referencing C++ code (It's an unreal engine project). 

> According to the flamegraph, the runtime is dominated by zip compression

Is it intentional that the compression here happens even without the -z flag? We would like these to be compressed of course, but for the purposes of this test we weren't providing the flag.

> Do the final source bundles end up unreasonably large?

Yeah, the source bundles add multiple GB to the resulting structure.

**Comment by donalmacc** [comment]
Hey, and apologies for the delay here. 

The source bundle is huge, and likely not compressing properly. It's about 2.5GB for our project, (and doesn't unzip properly on my windows machine, so I can't see if it's correct.).

**Comment by Swatinem** [comment]
Also sorry for the delay :-)

2.5G sounds unreasonably large. As I said, SourceBundles are zip files, but with an additional header in front, thats why some zip tools fail on them, while others succeed without any problem.

Alternatively, you can also try `sentry-cli debug-files bundle-sources`. This has a couple of default filters, in particular a filter for file size, so it will skip very large source files. The default is 1M per file.

It will also print warnings for files that exceed that size. Maybe this will  give a hint that some file is being zipped up which shouldn’t be.

**Comment by donalmacc** [comment]
@Swatinem - I've figured this out. running `sentry-cli debug-files bundle-sources` took 10 seconds, generated a 60MB zip file that expanded to 300MB, but only listed that it was ignoring a handful of files. I stopped at that point and took a look in anger today when getsantry pinged me.

https://github.com/getsentry/sentry-cli/blob/master/src/utils/dif_upload.rs#L1111 - I put that filter in symsorter and it took 10 seconds to run all of a sudden! 

```    if path.ends_with(".pch") {
        return false;
    }```

sentry-cli doesn't log (even on debug) that it's skipping PCH's. 
Stripping back the filter to ignore PCH's, even without the large-file ignore fixes it for us.

Would you take a PR with the sentry-cli filter ported to symbolicator?

**Comment by ashwoods** [comment]
@donalmacc Thanks for the update. We currently are a bit backlogged, picking this topic up this week.
