### ISSUE TITLE
Building symbolicator from source for use with Sentry

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/symbolicator#122]
I have symbolicator running on my system, and it's returning reasonable-looking results when I curl minidumps to it, however I can't seem to get a pip install of Sentry 9.1.2 talking to it. I did the required conf setup (https://github.com/getsentry/symbolicator#usage-with-sentry), but it appears that symbolication is occurring when I send the same minidumps to my test Sentry instance (for example, I get errors in the UI about symbol files which I know are missing).

But the stdout from my Symbolicator instance is not showing it having serviced any requests, so it seems like Sentry is doing its own thing internally. Do I need to build the master branch of Sentry in order to get Symbolicator support, or is there some other piece I'm missing here?

**Comment by untitaker** [comment]
Sentry 9 does not use Symbolicator. The documentation is there for usage from master right now. I believe we should update the README to make this clear.

**Comment by mikepurvis** [comment]
Okay, thanks. Yes, agree that the documentation could be clearer on this point.

Is there a timeline for releasing Sentry 10? I'm not keen to run unreleased software in production, so I'd like to understand what my time horizon is here.

**Comment by jan-auer** [comment]
Sentry 10 is probably still a few months out. If you like to follow the progress, have a look at https://github.com/getsentry/onpremise where we're providing a more modern setup that also includes symbolicator.
