### ISSUE TITLE
VS2022 paths are incorrectly parsed by proxy

### ISSUE THREAD

**Issue by donalmacc** [getsentry/symbolicator#1220]
Me again!

### Environment

Visual Studio 2022, Symbolicator 23.6.1 (and head). 

### Steps to Reproduce

1. Load minidump in Visual Studio 202
2. Add http://localhost:3021/proxy to the Symbol Paths
3. Run `symbolicator run -c config.yml`
4. Click "Load Symbols" in VS2022

### Expected Result

`parse_symstore_path` is called with "/Foo.pdb/ABCDEFG/Foo.pdb", and it parses `leading_fn`, `signature`, and `trailing_fn` to:
`Foo.pdb`, `ABCDEFG`, `Foo.pdb` respectively

### Actual Result

`parse_symstore_path` is called with "Foo.pdb/ABCDEFG/Foo.pdb". The code that splits this is
```
    let mut split = path.splitn(4, '/');
    // Skip the leading / that the path contains
    split.next()?;
    let leading_fn = split.next()?;
    let signature = split.next()?;
    let trailing_fn = split.next()?; <==== This errors
```

The first call to split.next is incorrect in this case, because the "path" doesn't begin with a /

**Comment by Swatinem** [comment]
Thats probably a problem with the path matcher. these two things need to be synchronized.
And TBH, the proxy is a rarely used thing, so it is under-tested. This means its a good opportunity to write a proper test for it, so it will not be causing any more problems.

**Comment by donalmacc** [comment]
Thanks. The proxy functionality is _super_ useful for us, so I'm happy to keep  banging on it and trying to help out where I can.
