### ISSUE TITLE
Is it ready for production for general apps, or is it only to be used in combination with Sentry?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/symbolicator#1232]
Hi thanks for the library! I wonder whether it is ready for production for general apps, or is it only to be used in combination with Sentry?

**Comment by Swatinem** [comment]
It is very much specific to Sentry, but certainly usable for outside consumers as well.

What is your specific usecase?

**Comment by fzyzcjy** [comment]
@Swatinem Thanks. Symbolicating my app, mainly consist of Dart (Flutter), Rust, Android, iOS.

**Comment by fzyzcjy** [comment]
More specifically, here is the usage --> https://github.com/getsentry/symbolicator/issues/1234
