### ISSUE TITLE
Handle cases when S3 contains gzipped .so symbols

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/symbolicator#1233]
Hi thanks for the lib! However, my S3 contains gzipped .so symbols, instead of raw .so files, because they are so huge and should be compressed. Therefore, I would appreciate it if symbolicator can understand those .gz files.

**Comment by Swatinem** [comment]
We should transparently decompress files no matter from which sources they are loaded:

https://github.com/getsentry/symbolicator/blob/ef0d656c48f0549c5bf6f5129ca360528e086991/crates/symbolicator-service/src/utils/compression.rs#L7-L14

**Comment by fzyzcjy** [comment]
@Swatinem Wow that's helpful, thank you!
