### ISSUE TITLE
Symbolicate when already know which .so file to use?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/symbolicator#1234]
Hi thanks for the library! I wonder is there a shortcut to symbolicate when already know which .so file to use? In my scenario, I have app version (say v1.2.3), and stack trace to be symbolicated (say addr 0x12345), and the symbol file to be used (say app-v123.so).  I can determine the exact .so to use, since I know the .so for the exact version.

Currently, if I understand correctly, symbolicator is something like:

* Fetch and cache various symbol files
* Auto choose best matching file
* Run symbolication

However, it would be great to have something like `addr2line`, `flutter symbolize`, `retrace`, etc. In other words, something like:

```
the-proposed-function --symbols app-v123.so --stack my-stack-trace.txt --output the-symbolicated-stack.txt
```

The most attractive thing of symbolicator is that, it can handle various kinds of symbols correctly. In other words, I no longer need to run many tools like `flutter symbolize`, `retrace` etc, but only one single tool!

---

EDIT: After writing these paragraphs I find the answer: https://github.com/getsentry/symbolic

Btw it would be great if symbolicator could hint users about symbolic :)

**Comment by Swatinem** [comment]
Well yes, `symcache_debug` from symbolic probably does that for a single frame, yes. Symbolicator / symbolicli as you said wraps that with more functionality to fetch symbol files also from external sources like microsoft, and processes whole minidumps.
You can combine that with `symsorter` to sort your symbol files into a local directory that is configured in symbolicator.
