### ISSUE TITLE
Symsorter generates bad ids with many zeros on .o files lacking .note.gnu.build-id and .note.ABI-tag sections.

### ISSUE THREAD

**Issue by zokrovi** [getsentry/symbolicator#1240]
### Environment

Symbolicator 0.7.0 (specifically symsorter) built for Centos 7.9

### Steps to Reproduce

Built and installed the project.
Run symsorter -zz --output symbols .
It goes and creates unified debug info for all executables, libraries, and including .o files.

or more synthetically:

Write a hello world, and compile to a .o file with -c, then run symsorter on it. 

### Expected Result

It should error on .o files that it cannot get a build-id from. 

### Actual Result

Instead it extracts some bytes from the ELF header of those .o files that usually contain a long string of zeros, plus a few random bytes, and sorts them to the 00/ folder, without error.

This seems to be a problem unique to Linux, as we didn't observe it on Mac or Windows. 
There is a related issue here https://github.com/getsentry/symbolicator/issues/465 and the fix here **https://github.com/getsentry/symbolicator/pull/469 however that does not fix this case since the ids are not completely empty - they have some random elf header bytes in them.

**Comment by loewenheim** [comment]
Thank you for the report!

**Comment by zokrovi** [comment]
On Ubuntu, it seems .o files will have an NT_GNU_PROPERTY_TYPE_0 field which symsorter gets the id from. But you can still reproduce the issue if you do `objcopy --remove-section .note.gnu.property test.o` . My Centos doesn't produce these sections naturally, without needing to strip them.

It would seem this issue is platform independent, and also the latest symsorter release does this too. I just tested on Windows against an ELF .o file and it created an id of \fa/1e0ff343798ba48c85fe00000000e80/executable . If we look closer at the object file in a hex editor, we see those bytes are coming from a random bit of the ELF header. And given a build-id is based on a SHA hash, we shouldn't expect to see so many zeros!

test object file attached, compile with gcc -c test.c (and remove the .note section as above if on Ubuntu)
[test.zip](https://github.com/getsentry/symbolicator/files/11957015/test.zip)

**Comment by zokrovi** [comment]
This is not just .o files either. For an _in-the-wild_ example, here's **libmkl_vml_avx2.so** - a shared library - from this .deb package:
http://ftp.de.debian.org/debian/pool/non-free/i/intel-mkl/libmkl-vml-avx2_2020.4.304-4_amd64.deb

Symsorter gave this id for it:
`libmkl_vml_avx2.so (lib, x86_64) -> symbols\00/0000000022000000000000000000000/executable`

If we run  `readelf -Wn mkl/libmkl_vml_avx2.so` on it we get nothing. We should hit an error in this case, but don't.

**Comment by zokrovi** [comment]
I propose removing this XOR 'hash' in symbolic's `symbolic-debuginfo/src/elf.rs`:

https://github.com/getsentry/symbolic/blob/11472bfbb31f2ed76802ff50bfc40a2b0852ee1b/symbolic-debuginfo/src/elf.rs#L385C1-L396C1

This hash creates zero filled ids and makes collisions very likely. These collisions mean misleading sentry stack-traces. It would be better to not generate them at all and error if an id is not present by just returning `DebugId::default()`.

**Comment by kahest** [comment]
We are currently not looking to make changes to the hashing because it affects many components and product parts and it would introduce other drawbacks (see https://github.com/getsentry/symbolicator/issues/1240#issuecomment-1670920746). 

I created followup issues:
- https://github.com/getsentry/symbolicator/issues/1280
- https://github.com/getsentry/sentry-docs/issues/7610

**Comment by zokrovi** [comment]
@kahest not changing the hashing is understandable to maintain the same behavior. But couldn't we introduce an extra function like strict_debug_id(...) that doesn't have the unreliable hashing (and returns the default ID when unavailable instead)? This way symsorter could have a strict mode when calculating ids, and would error out as expected when an id cannot be found.

**Comment by kahest** [comment]
@zokrovi we'll discuss your suggestion and follow up here!
