### ISSUE TITLE
Reprocessing periodically stuck short of completing

### ISSUE THREAD

**Issue by quickstark** [getsentry/symbolicator#1319]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This behavior is inconsistent, so unclear the steps to reliably reproduce, but occasionally when executing the option to "Reprocess Events" (in this case, for a minidump) the process gets stuck short of completing (e.g. 266/300) and the underlying Issue page is never rendered.

This historically requires Sentry Ops to un-stick the job.

Would be better to have an automated way to catch and un-stick this without human intervention.

(Note: Submitting on behalf of a customer. Reach out internally to Dirk Nielsen for more context.)

### Expected Result

Reprocessing works without hanging on the last event.

### Actual Result

No current screenshots, but simply shows a Reprocessing message on the Issue page with the count (479/480).

![image](https://github.com/getsentry/sentry/assets/17515078/bb6c17b8-20c3-4f60-a158-c77aed4b1559)
### Product Area

Issues

**Comment by ashwoods** [comment]
Thank you for your report @quickstark. We will be looking into this shortly.

**Comment by yuval-sentry** [comment]
@Swatinem Shall we mark this as resolved?

**Comment by ashwoods** [comment]
We have one report left that we want to look at before closing  go this.

**Comment by ashwoods** [comment]
Marking this as resolved. Please let us know if you run into this again.

**Comment by yuval-sentry** [comment]
Thank you!
