### ISSUE TITLE
Patch sentry-getsentry/symbolicator:23.9.1 vulnerabilities

### ISSUE THREAD

**Issue by ziler-orca** [getsentry/symbolicator#1326]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0

### Steps to Reproduce

The sentry-getsentry/symbolicator image `23.9.1` has several vulnerabilities. Please see attached.

[symbolicator_cves.xlsx](https://github.com/getsentry/self-hosted/files/12924241/symbolicator_cves.xlsx)

### Expected Result

Patch the vulnerabilities.

### Actual Result

Please refer to spreadsheet attached above for details.

**Comment by Swatinem** [comment]
All of these are in the base image packages, no are in symbolicators Rust code or any of the Rust dependencies.

So is there anything other to do here than to run an `apt upgrade` in the base docker image?

**Comment by hubertdeng123** [comment]
> So is there anything other to do here than to run an apt upgrade in the base docker image?

Guess not then 🙂

So the `apt upgrade` should be run in https://github.com/getsentry/symbolicator/blob/master/Dockerfile?
