### ISSUE TITLE
Mistaken download of HTML file from dev.azure.com during C# symbolication

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolicator#1457]
We have seen cases of portable pdb files with source links to `dev.azure.com/path/to/source/file`. Trying to fetch such a file results in a login page being downloaded and used to apply source context, which is clearly nonsensical.

The page in question can be found by running
```
❯ curl -L 'https://dev.azure.com/foo/bar.cs'
```

The best thing to do would be to download the file and use it, but failing that, it would be better to apply no source context.
It's currently unclear to me if downloading such a source file is even possible in principle. We already have this comment that seems apposite:
https://github.com/getsentry/symbolicator/blob/5499fff962b4abe4295907622c3213f2a4ed57d3/crates/symbolicator-native/src/symbolication/module_lookup.rs#L411-L412

**Comment by klemmchr** [comment]
We are having the same issue. I don't have insights on how symbolicator works internally but I find it a bit strange that it attempts to download external code instead of using the source code provided. We are using the [MSBuild](https://docs.sentry.io/platforms/dotnet/configuration/msbuild/#optional-msbuild-properties) integration which has a flag to also upload sources. My assumption would be that these source files would be used when displaying in-app stacktrace sources.

**Comment by loewenheim** [comment]
It _should_ already work like that—the source should only be downloaded if it's not available. Are you self-hosting? Do you have an event you can link to that exhibits this problem?

**Comment by bruno-garcia** [comment]
> It should already work like that—the source should only be downloaded if it's not available. Are you self-hosting? Do you have an event you can link to that exhibits this problem?


@loewenheim @vaind Do we look at sources in the `.pdb` too before downloading? In .NET the source can be bundled in the debug info file (PDB) as well as uploaded in a _sourcebundle_.

**Comment by loewenheim** [comment]
> [@loewenheim](https://github.com/loewenheim) [@vaind](https://github.com/vaind) Do we look at sources in the `.pdb` too before downloading? In .NET the source can be bundled in the debug info file (PDB) as well as uploaded in a _sourcebundle_.

Yes, we support that.

**Comment by klemmchr** [comment]
This seems to not be working correctly then. We're still seeing the Azure DevOps unauthenticated HTMl being used as source for our C# files.

**Comment by loewenheim** [comment]
Do you have a PPDB file for which this is not working that I can look at?

**Comment by klemmchr** [comment]
Nothing that I could send you publicly. Any chance I can send over one of it privately?

**Comment by loewenheim** [comment]
Yes, absolutely. My company address is sebastian.zivota@sentry.io.

**Comment by loewenheim** [comment]
Thank you. I'm investigating it right now.

**Comment by loewenheim** [comment]
Source extraction from portable PDBs seems to be working as intended. We still don't have a good answer for the problem of getting a login page when trying to download a source file from the internet. Ideas that were considered:
* Don't follow redirects. But there could be legitimate redirects that don't go to login pages, so this is too broad.
* Reject HTML files. But in the context of JavaScript, HTML files would be valid source files, so this also doesn't work in general.

**Comment by bruno-garcia** [comment]
> Don't follow redirects. But there could be legitimate redirects that don't go to login pages, so this is too broad.


This sounds fair to me. If we get requests later we can consider an option to turn it on, for example.

**Comment by loewenheim** [comment]
For azure specifically, this should be fixed as of https://github.com/getsentry/symbolicator/pull/1533. We might reopen this if we see other cases.
