### ISSUE TITLE
Consider running release workflows on an older version of Ubuntu (to avoid glibc versioning issues)

### ISSUE THREAD

**Issue by vorporeal** [getsentry/symbolicator#1466]
Tried to use the pre-built `wasm-split` binary in our application's release workflow and ran into glibc versioning issues due to the fact that we run our workflows on Ubuntu 20.04 and y'all use `ubuntu-latest` to build release binaries.

It would be worth trying to use `ubuntu-20.04` as the value of `runs-on` instead of `ubuntu-latest`, as it'll allow the compiled binary to run on older distributions of Linux that include older versions of glibc.

(We're using `cargo install` to build the binary from source, but it would be nicer/faster to use the official pre-compiled one instead.)

**Comment by loewenheim** [comment]
Hi, thank you for the suggestion, we'll discuss it.
