### ISSUE TITLE
How to use Symbolication Request with no image_addr and image_size。 like addr2line -Cie xx.so -f 0000000004cce220

### ISSUE THREAD

**Issue by Doslin** [getsentry/symbolicator#1474]
![image](https://github.com/getsentry/symbolicator/assets/29807388/4c73e1f5-7f47-47c9-810e-c364007ac5fe)

**Comment by Swatinem** [comment]
That is not possible at least for native. Other platforms may not require those fields.

If you already have a module-relative addr and a single module (vs an absolute instruction addr), just give it `"image_addr": "0x0"`. I believe `image_size` is optional, but I might be wrong.
