### ISSUE TITLE
Service 'symbolicator-cleanup' failed to build

### ISSUE THREAD

**Issue by cdd111** [getsentry/symbolicator#151]
when I run ./install.sh  , get this error:
Service 'symbolicator-cleanup' failed to build: Get https://us.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
![Uploading 微信图片_20191115112244.png…]()

**Comment by cdd111** [comment]
![微信图片_20191115112244](https://user-images.githubusercontent.com/12994339/68914746-81aa4880-079a-11ea-80b2-a9bb85ad8009.png)

**Comment by untitaker** [comment]
cc @BYK, perhaps we can use a different mirror than `us.gcr.io`

**Comment by BYK** [comment]
@cdd111 looks like you have an issue connecting to the Google Cloud Repository. Not sure what we can do to help you at the moment as we cannot push the images to a closer location to you easily. Are you able to use a proxy or something in the middle that can help speed it up?

@untitaker I'm all in start pushing these images to Docker Hub, what do you think?

**Comment by untitaker** [comment]
I don't know enough about where docker hub is to know if this helps with
the blocking

**Comment by BYK** [comment]
@untitaker seems like they do have a mirror in China since 2017: https://www.docker.com/docker-news-and-press/docker-brings-docker-public-registry-china-expand-developer-adoption-and-fuel

**Comment by cdd111** [comment]
@BYK @untitaker thanks, So I re-install the docker use the china mirror and rebuild the sentry?

**Comment by BYK** [comment]
@cdd111 - that should do it, yeah.

**Comment by Swatinem** [comment]
I believe this is stale. We should have docker images built for all of this.
