### ISSUE TITLE
Conditionally treat downloaded HTML files as errors

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolicator#1526]
We have seen cases where trying to fetch a native source file from a web source can turn up a HTML login page, which is then used for source context. Obviously this is not desirable. On the other hand, in a JS context, it's totally reasonable to have a HTML file as the source file.

I propose we add a flag `may_be_html` (name subject to change) to `HttpRemoteFile` that tells the downloader whether a returned HTML file is legit or an error. We would always set this to `false` from native and true from JS.

**Comment by bruno-garcia** [comment]
Relates to:

* https://github.com/getsentry/symbolicator/issues/1457

**Comment by loewenheim** [comment]
Possible alternative solution: reject HTML pages received after a temporary redirect, which should be a good heuristic for a login page.
