### ISSUE TITLE
Keep filename and abs_path from foreign classes

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/symbolicator#1552]
This code currently removes the filename and abs_path from stack traces:
https://github.com/getsentry/symbolicator/blob/master/crates/symbolicator-proguard/src/symbolication.rs#L340-L343

```
 // clear the filename for all *foreign* classes
 if mapped_frame.module != bottom_class {
       mapped_frame.filename = None;
       mapped_frame.abs_path = None;
}
```

As a result, source code context cannot be show in the stack as there is no file name to fetch the context.

**Comment by loewenheim** [comment]
Hi! This would be a simple enough change to make but as discussed on Slack I'm ambivalent about doing this. I believe the reasoning for why this code exists is as follows. Consider this small example proguard file:
```
com.example.application.Main -> f:
# {"id":"sourceFile","fileName":"Main.java"}
    3040:3042:java.io.PrintWriter com.example.application.util.PrintWriterUtil.createPrintWriterOut(java.io.File):40:42 -> a
    3040:3042:void printConfiguration():243 -> a
    3040:3042:void execute():80 -> a
```

This indicates that in the (synthetic) line number range 3040:3042 of class `f`, you are in 
* `com.example.application.util.PrintWriterUtil.createPrintWriterOut`, which was inlined into 
* `com.example.application.Main.printConfiguration`, line 243 in `Main.java`, which was in turn inlined into 
* `com.example.application.Main.execute`, line 80 in `Main.java`.

But obviously `createPrintWriterOut` might not itself be defined in `Main.java`—it was merely inlined there. And the reason to believe it comes from a different file is the fact that it has a different class name.
