### ISSUE TITLE
Question: Grouping support

### ISSUE THREAD

**Issue by dive** [getsentry/symbolicator#196]
Hello there,

I have a question about grouping possibilities. As I can see from the documentation, there is no support for grouping (something like, generate a hash from the thread where application crashed). And I wonder how you solve this on your side? In general, we want to produce hashes for similar crashes during the symbolication to be able to group them in another system.

So, what do you think, is it okay to prepare a PR for the `symbolicator` and extend it with the desired functionality? Or it is out of the scope of the project?

Thanks for the answer. And thank you for this handy service!

**Comment by untitaker** [comment]
We really don't want this functionality in Symbolicator. Do you need this feature in the context of Sentry or when using Symbolicator in another system? Sentry does grouping (that's the most important thing it does for errors), even after event processing.

**Comment by dive** [comment]
@untitaker, we want it for our internal system (no Sentry, only Symbolicator), and I really do not want to maintain a fork because you guys are much better in Rust and all these internal stuff. I understand your desire to separate things properly, so, I think that the question has been resolved.

Thanks for the quick answer, @untitaker!
