### ISSUE TITLE
Prepare debug files for a custom Symbol Server

### ISSUE THREAD

**Issue by dizer** [getsentry/symbolicator#198]
Some of our debug files exceed 2GB limit and unable to be uploaded directly. So now we are testing Symbol Server (S3) and it looks fine. 

But the problem is a directory layout. We have 3 platforms and all of them require own paths and utils to generate them. 

Is there any way to simplify layout generation? Via CLI or proxy (does https://github.com/getsentry/symbolicator/ may help)?

**Comment by mitsuhiko** [comment]
The layout has been added to sentry now so you can use symsorter directly.

**Comment by dizer** [comment]
Wow, thank you!
