### ISSUE TITLE
Validate that source IDs are distinct

### ISSUE THREAD

**Issue by untitaker** [getsentry/symbolicator#20]

**Comment by untitaker** [comment]
**Also make sure that the cache keys actually do not conflict after running through `safe_path`**

**Comment by jan-auer** [comment]
@untitaker Sounds like now is a good time to verify this.

**Comment by untitaker** [comment]
So I would do:

* Throw 400 Bad Request here
* In Sentry, enforce this in schema validation

**Comment by jan-auer** [comment]
Sentry already enforces this.

**Comment by Swatinem** [comment]
https://github.com/getsentry/sentry/pull/33909 gives a new uuid to sources when their configuration is changed, or they are newly created.
Not quite sure what else can be done on symbolicators side.
