### ISSUE TITLE
Issue with symbolicating with a particular system symbol file CFNetwork

### ISSUE THREAD

**Issue by Aashima89** [getsentry/symbolicator#207]
while trying to symbolicate one stacktrace 

trace from crash report
```
5   CFNetwork                           0x0000000185d1fe88 0x185b66000 + 1810056
```

file got downloaded in my local cache
symbolicator response

```
{\"status\":\"missing_symbol\",\"original_index\":5,\"instruction_addr\":\"0x185d1fe88\",\"package\":\"/System/Library/Frameworks/CFNetwork.framework/CFNetwork\"}
```

Not sure why it says missing symbol when all required things are available. Found this issue for this particular system symbol file in multiple stacktraces

**Comment by Swatinem** [comment]
@Aashima89 sorry for the delay of more than 1 year here. Are you running a self-hosted version? Also, which macos version is that library from?

Or is this issue obsolete by now and we can just close? ;-)
