### ISSUE TITLE
Document configuring symbolicator for use with Sentry 10

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/symbolicator#245]
Hi— I'm using Symbolicator with Sentry in conjunction with a small external service which supplies debug symbols stored elsewhere. I can get it working fine when I run symbolicator standalone and directly curl my minidumps at it, but I can't figure out how to get the onpremise deployment to take the config. I thought initially that maybe the `symbolicator.options` dict from the main `config.yml` was extracted and passed through somehow:

https://github.com/getsentry/onpremise/blob/a549ab1300f94149bf347df9277cf7bc50f0e5d7/sentry/config.example.yml#L69-L71

However, upon looking at the running `sentry_onpremise_symbolicator_1` container, it appears that there's no config at all in there, and the process is `/bin/symbolicator run` with no `-c` flag, which per the docs here means it is running entirely with the default settings.

It seems the intent is for symbol servers to be configured on a per-project basis in Sentry, and the relevant ones are passed to Symbolicator on every request. This is not ideal for me as it makes it more difficult to test Symbolicator's behaviour in isolation as the request is more complicated and there are unknown layers of caching going on in the middle. It's also likely not to be a great fit for my org as we may end up with many similarly-configured minidump projects, all using the same source, where we would not want to have to set it up each time.

Is there a plan to support/document a mechanism for injecting symbolicator config with the onpremise setup method?

**Comment by flub** [comment]
You can configure global symbol servers using the `sources` option in the symbolicator config file (https://getsentry.github.io/symbolicator/#configuration) which takes sources information in the same format as the API.  This should allow you to configure sources used by all requests in one location.  I'm not familiar with the onprem setup, but I imagine it's possible to start symbolicator there with a custom config file.

**Comment by flub** [comment]
https://forum.sentry.io/c/on-premise might be a better place to ask onprem-specific questions btw.

**Comment by mikepurvis** [comment]
It's not currently (easily) possible to specify custom configuration for symbolicator under the Sentry 10 docker setup, but https://github.com/getsentry/onpremise/pull/566 adds that capability. If/when that change merges, the remaining task on the Symbolicator end could be just to document that or link to the relevant documentation in Sentry.

**Comment by Swatinem** [comment]
The onpremise/self-hosted PR you linked has been merged since.

Otherwise the source configuration from the config file is being overwritten completely by the source info within the request, and sentry itself always attached the sentry source itself. So configuring sources within sentry is the supported way here. However we would always love contributions to docs that make this more obvious.
