### ISSUE TITLE
Add WASM Support

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/symbolicator#300]
Add support for WASM based on the outcomes of https://github.com/getsentry/symbolic/issues/290.

Since WASM does not map object files into memory out current idea of our protocol likely needs to change. At the moment we use `instruction_addr` to map into a unified memory space. We then use the information of the `debug_meta` to find the right images for those instruction addresses. Later in the Sentry UI (for instance) we map the instruction addresses into relative addresses for display purposes only.

With WASM the concept of instruction addresses becomes a bit weird. First of all there are really no absolute addresses and addresses themselves are not unique. One way would be to encode a module ID into the instruction address, the other option would be to add a second value (`image_idx` for instance) which switches the addr to be relative within the image (as identified by the index in the debug image array).

Given what we the reality is on the ground we likely use offsets within the entire WASM file as input, not offsets within the `Code` section only. While this is a bit odd as the DWARF file is based on `Code` offsets it's more consistent with what browsers are sending and how users are likely to be interfacing with it.

**Comment by jan-auer** [comment]
👋
