### ISSUE TITLE
Override environment tag for sentry integration

### ISSUE THREAD

**Issue by mk4437** [getsentry/symbolicator#315]
We're using symbolicator with sentry to track any symbolicator errors.  The environment tag is always getting set to _release_, and I could not find a way to override it.  We'd like to set it to our deployment environment using an envar, similar to what we do with our java and python sentry integrations.

**Comment by flub** [comment]
I believe the sentry-rust SDK will respect a `SENTRY_ENVIRONMENT` env var (https://github.com/getsentry/sentry-rust/blob/c9ff86c55c3088288b5bc357fe89ee7711f59933/sentry/src/defaults.rs#L93) and it doesn't look like symbolicator customises this.  So you should be able to use this?

**Comment by flub** [comment]
Oh, this is probably affected by https://github.com/getsentry/sentry-rust/pull/293. So we need to manage to upgrade the SDK for the next release.

**Comment by mk4437** [comment]
It looks like the SDK fix didn't make it to 0.3.2.  Can we expect a new release sometime soon?

**Comment by flub** [comment]
Hey, apologies for that.  We need to get better at releasing regularly.  We just published 0.3.3, let me know if this still didn't fix it.

**Comment by msaarinen** [comment]
I confirm this is working now with 0.3.3.  Thanks for the assistance.

**Comment by mk4437** [comment]
I confirm this is working now with 0.3.3.  Thanks for the assistance.
