### ISSUE TITLE
Run integration tests against Sentry

### ISSUE THREAD

**Issue by jan-auer** [getsentry/symbolicator#318]
While symbolicator is an independent service, its main use is in Sentry. Since changes to symbolicator may break integration tests in Sentry, it could be useful to run a subset of them on PR builds.

There is prior art. In [Relay](https://github.com/getsentry/relay), we run the onpremise test suite on the master branch, which creates a full Sentry setup (without test mocks), and ingests an event.

For symbolicator, this would mean:

- Run the (or an equivalent of the) "symbolicator_integration" test suite from Sentry.
- This test suite ships snapshots, which we must be able to update to get tests passing.
- Ideally, this does not use a mocked Sentry setup, but proper configuration like onpremise has.

**Comment by armenzg** [comment]
Hi @jan-auer 
For relay I assume you refer to [this Integration Tests](https://github.com/getsentry/relay/runs/2217675677) (defined in [ci.yml](https://github.com/getsentry/relay/blob/master/.github/workflows/ci.yml#L174)).

Are these the integration tests?
https://github.com/getsentry/relay/tree/master/tests/integration

**Comment by jan-auer** [comment]
For Relay, it would actually be the [`relay_integration`](https://github.com/getsentry/sentry/tree/917aecca030c837ce06553aac2c0ff11b2283f14/tests/relay_integration) test suite in Sentry. This repository doesn't have any dependencies on Sentry, but Sentry the other ways does. This is why we have all the integration tests implemented there.

**Comment by armenzg** [comment]
Fixed via https://github.com/getsentry/symbolicator/pull/500
