### ISSUE TITLE
Support source code fetching via debuginfod

### ISSUE THREAD

**Issue by fche** [getsentry/symbolicator#445]
Via pull #142 back in 2019, symbolicator learned to fetch debuginfo & executables from debuginfod servers.  The server also has a source code fetching webapi (`/buildid/HEXCODE/source/PATH`), which should not be too hard to make use of.  It does not supply a "bundle" in the sense of a zip file, but individual source files.

**Comment by vaind** [comment]
The new source-link support for PPDB should be a good step towards implementing this too. https://github.com/getsentry/symbolicator/pull/1103/files#diff-01996d90eae63193cc43413d280444d2271905de228d87dbaba4d5bfdc53f1d9R405

**Comment by fche** [comment]
By the way, the elfutils toolkit now includes a tool called "eu-srcfiles".   With that, it is possible to enumerate all known source files associated with a given binary/buildid known to a debuginfod fleet.  Further, the tool can download all of those source files and produce a single zip file.

% export DEBUGINFOD_URLS=whatever
% eu-srcfiles -e /bin/ls -z > foo.zip
% unzip -v foo.zip

https://developers.redhat.com/blog/2024/04/15/interns-experience-tool-development-growth-and-open-source-red-hat

**Comment by Dav1dde** [comment]
This is still not implemented and something we should consider implementing.
