### ISSUE TITLE
iOS symbol file download misses with 0.3.4

### ISSUE THREAD

**Issue by mk4437** [getsentry/symbolicator#561]
### Environment

How do you use Sentry?
Symbolicator self-hosted/on-premise v 0.3.4

### Steps to Reproduce

1. System posts crash report containing iOS system stacklines to /applecrashreport
2. Result is partially symbolicated (intermittent)
3. Manually post same crash report again to /applecrashreport
4. Result is fully symbolicated

### Expected Result

Result should have been fully symbolicated at step 2.  This behavior is intermittent and has not been reproduced when manually posting a crash report to symbolicator.  Also, it may not be all system symbols that fail for a given report but only some of them.

### Actual Result

We see an increase in missing system symbol file results from Symbolicator with our upgrade from 0.3.3 to 0.3.4.  We changed nothing in our configuration when going from 0.3.3 to 0.3.4 other than going from inline to container credential management for S3.

**Comment by mk4437** [comment]
We captured some trace logs from production.  I need to cross-reference these against information in other systems, so I'll have some more info to add here tomorrow.

**Comment by mk4437** [comment]
Attached are relevant portions from the trace logs from yesterday.  It shows three different requests within minutes of each other for an existing symbol file.  The first fails, the second succeeds, and the third gets from cache.  On two running instances of symbolicator, one may succeed while the other may not.

The failure gives the error "expected value at line 1 column 1" when parsing the response, which I see often in the logs whether the file exists at the location or not.
[symbolicator-trace-logs.txt](https://github.com/getsentry/symbolicator/files/7228476/symbolicator-trace-logs.txt)

**Comment by mk4437** [comment]
Here's our cache config.  I don't know whether how we have it is correct/advisable.
```
caches:
  downloaded:
    retry_misses_after: 0s
  derived:
    retry_misses_after: 0s
```

**Comment by Swatinem** [comment]
sorry for the delay here.

Which exact version (git hash) are you running?

The error message really looks like indicating a serde parse error, but it is weird that it only happens for the first time.

The current `master` version should be doing a few retry attempts in case things are failing.

**Comment by mk4437** [comment]
we've been using 0.3.4 tagged release 30cf693.

**Comment by Swatinem** [comment]
We will release `0.4.0` shortly, which includes the retry code that I mentioned.

**Comment by mk4437** [comment]
Thank you, we will be sure to try it.  If it would also be possible to get the response body string logged at some level for  errors such as this it would be most helpful.

**Comment by phene** [comment]
What's the latest on this?

**Comment by msaarinen** [comment]
We've upgraded to 0.4.2, so closing this issue.
