### ISSUE TITLE
wasm_split release for MacOS

### ISSUE THREAD

**Issue by bkotsopoulossc** [getsentry/symbolicator#564]
The repo currently releases builds of the `wasm_split` tool on linux, however it seems feasible to build and release it for MacOS as well. Is there interest in supporting this, and what would it take to do so? Thanks in advance!

**Comment by jan-auer** [comment]
Thanks, we'd definitely be open to build and release for macOS, too! Would you be up for a hacktoberfest contribution? :) 

The build workflow is located here: https://github.com/getsentry/symbolicator/blob/654086c9247f8915ca0b987645c618e7ac5eb598/.github/workflows/build.yml#L9-L48

Building and releasing macOS requires a second job running on `macos-latest` with the post-build steps updated:
- Remove objcopy, `dsymutil` is run automatically by cargo
- Change paths to publish dSYMs too

This would end up looking similar to [what we do in Relay](https://github.com/getsentry/relay/blob/c2daf430b8efa1d48ad7b2a7c666712ec51a3c13/.github/workflows/build_binary.yml#L35-L67).

**Comment by bkotsopoulossc** [comment]
@jan-auer sure thing, can you give me permissions to run github workflows so I can iterate a bit?
![image](https://user-images.githubusercontent.com/25588019/136586000-bb60e3b6-ef9e-4745-9ace-09ee3eb4b01a.png)
