### ISSUE TITLE
Investigate symbolicator on bullseye memory leaking

### ISSUE THREAD

**Issue by aminvakil** [getsentry/symbolicator#580]
Symbolicator still uses a very old Debian release for its docker container image, previous attempts to upgrade to more recent Debian versions have always resulted in a slow but steady memory leak.  As this is now true for multiple newer versions of Debian and the old release is getting rather older, we should figure out what the cause is and fix it.

----
Some initial investigation ideas:

Would it be possible to set up something very simple like set up a script which spins up the container and sends some of our minidumps in the test suite to it with curl, in a loop.  Even though that is the same minidump over and over it would still be interesting to see if that keeps increasing the memory or not.  Once that exist it might be interesting to see if symbolicator can then run under something like `cargo-valgrind` inside of the container and maybe it finds something interesting.

_Originally posted by @flub in https://github.com/getsentry/symbolicator/issues/578#issuecomment-968713404_

**Comment by jan-auer** [comment]
See also https://github.com/getsentry/symbolicator/pull/356#issuecomment-781990116

**Comment by Swatinem** [comment]
We tried this yet again, as we had enough internal changes (replaced breakpad C++ code; removed procspawn).

Though there is still a memory leak (or rather, monotonically increasing memory usage) that we observe.

**Comment by Swatinem** [comment]
switching the allocator to jemalloc did not only fix the memory leaks, but also reduced the baseline memory usage considerably.
