### ISSUE TITLE
Newer versions break submission from .NET System.Net.Http

### ISSUE THREAD

**Issue by blattersturm** [getsentry/symbolicator#582]
### Environment

How do you use Sentry? Not.
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?) N/A

Which SDK and version? N/A
e.g: JavaScript 5.11.1, .NET 1.2.0

### Steps to Reproduce

```csharp
            var uri = m_config.GetValue("SymbolicatorUri", "http://localhost:3021") + "/minidump";

            // try having it parsed by Symbolicator
            var symResponse = await m_httpClient.SendAsync(new HttpRequestMessage()
            {
                RequestUri = new Uri(uri),
                Method = HttpMethod.Post,
                Content = new MultipartFormDataContent()
                {
                    { new StreamContent(ms), "upload_file_minidump" }
                }
            });

```

### Expected Result

Processing the minidump and returning a symbolicated response.

### Actual Result

```json
{"detail":"missing minidump"}
```

### Additional info

I filed https://github.com/rousan/multer-rs/issues/41 since 'axum' depends on this (buggy) library for multipart parsing but it seems to not have been acted upon yet.

**Comment by jan-auer** [comment]
Thank you for this and the upstream the bug report! We'll try to look into this in time, potentially we can provide the bug fix. 
In the meanwhile, we'll keep this on our backlog.

**Comment by Swatinem** [comment]
Looks like the underlying dependency was patched in the meantime, so I will close this for now, please reopen if this continues to be a problem.
