### ISSUE TITLE
wasm-split: support external_debug_info

### ISSUE THREAD

**Issue by bkotsopoulossc** [getsentry/symbolicator#614]
The idea of using wasm-split is that we build with debug symbols, then run the split util on it to separate it into two files. This is similar to the emscripten command `-gseparate-dwarf`. This command embeds a custom section in the main binary that is a pointer to the debug symbol binary. This pointer defaults to the name of the debug file. The separate-dwarf command also has an option `SEPARATE_DWARF_URL` to specify a specific URL to host the debug symbol file.

This is used by browsers to load debug symbols and allow debugging or symbolicated traces directly in the browser. It's somewhat orthogonal to supporting symbolicated wasm stack traces with sentry, server side. It would be awesome to support both.

I'd like to add support for this flag in wasm-split, with potentially the default and URL override option. Is there appetite for that?

Some more docs:
- Emscripten code: [link](https://github.com/emscripten-core/emscripten/blob/main/tools/building.py#L1186)
- Wasm spec for external dwarf: [link](https://yurydelendik.github.io/webassembly-dwarf/#external-DWARF)
- Another spec: [link](https://github.com/WebAssembly/tool-conventions/blob/08bacbed7d0daff49808370cd93b6a6f0c962d76/Debugging.md#L19)
- Chrome support: [link](https://monorail-prod.appspot.com/p/chromium/issues/detail?id=1064248)

@Swatinem @jan-auer ?

**Comment by Swatinem** [comment]
Absolutely, this sounds like a nice addition

**Comment by bkotsopoulossc** [comment]
@Swatinem I also wonder what is the end game for the wasm-split tool? https://github.com/WebAssembly/tool-conventions/issues/133 suggests that there is work in progress to embed build ID at build time. Once that lands in the various layers of the stack, wasm-split won’t be needed right? But we’re not sure how long that will take…
