### ISSUE TITLE
Extend SymbolProvider to collect and preserve errors encountered during stack walking

### ISSUE THREAD

**Issue by relaxolotl** [getsentry/symbolicator#692]
symbolicator implements `SymbolProvider` from rust-minidump in order to be able to perform stackwalking through minidumps. rust-minidump offers a few error types for issues that may crop up when `SymbolProvider` does its work: [`SymbolError`](https://github.com/luser/rust-minidump/blob/4042a9216a8be0add6d35de8df2d68e2decd12cd/minidump-processor/src/symbols.rs#L54-L55) for generic errors, and [`FillSymbolError`](https://github.com/luser/rust-minidump/blob/4042a9216a8be0add6d35de8df2d68e2decd12cd/minidump-processor/src/symbols.rs#L56-L58).

symbolicator currently uses `FillSymbolError` for the purpose of, to quote `rust-minidump`: [(making it) so that the caller can distinguish between "we had symbols, but this address didn't map to a function name" and "we had no symbols for that module" (this is used as a heuristic for stack scanning.)](https://github.com/luser/rust-minidump/blob/c48c53566187e1d6644b95656796e84ad84ece00/breakpad-symbols/src/lib.rs#L243-L246) `rust-minidump` also offers rudimentary diagnostics via `SymbolProvider::stats` and `ProcessState::symbol_stats` in the form of basic counts of missing/unparseable symbols. There is also existing functionality to [collect and return a list of missing `DebugId`s](https://github.com/getsentry/symbolicator/blob/b3c76e4d21a0e5464adf4ccdcb00b8612439c5e5/crates/symbolicator/src/services/symbolication.rs#L1538-L1541) during stackwalking.

It would be a good idea to look into extending `SymbolProvider` locally to collect all of the errors that might occur during stackwalking, and offer an API that exposes those. Perhaps there are certain parsing errors (`SymbolError::ParseError`) that would be useful to collect for diagnostic purposes. Maybe there're errors when loading specific modules (`SymbolError::LoadError`) which would be useful to investigate. Maybe there are errors that currently have no representation in the current set of error types that should be added and collected. 

Currently there does not exist concrete use cases or examples of errors that would be desirable to capture during stackwalking, so this issue exists to collect those in a central place. Suggestions/feedback are welcome.

**Comment by Swatinem** [comment]
@loewenheim I think we do capture these errors now?

**Comment by Swatinem** [comment]
we internally log `rust-minidump` internal `tracing` warnings, and we are also logging errors when dealing with cfi files. any problem there should be visible in the module / candidates list.
