### ISSUE TITLE
Make LRU auth caches configurable

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/symbolicator#76]
Currently all the LRU caches for auth info we have (S3 and GCS) use a hardcoded max (of 100 items). We should make this configurable and also evaluate what a reasonable default is.

**Comment by jan-auer** [comment]
This seems to be working fine, although this is currently hard to monitor. I will be adding metrics for hits and misses so that we can evaluate this.

**Comment by Swatinem** [comment]
This was implemented in https://github.com/getsentry/symbolicator/pull/911
