### ISSUE TITLE
Symbolicator cannot parse DWARF spec version 5

### ISSUE THREAD

**Issue by zachhilman** [getsentry/symbolicator#855]
Recently, a new version of the DWARF debug info spec was released, version 5: https://dwarfstd.org/Dwarf5Std.php
Additionally, modern versions of clang/gcc are adopting this new version: https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Clang-DWARFv5-Default

I was demoing sentry-native on linux, and found that no matter what I did the symbolicator would report my binaries or debug companions as 'broken'. I thought this was bizarre as they were really basic programs compiled with `clang++ -O0 -g ...` and gdb/lldb worked fine, but it turns out its because of DWARFv5. After passing `-gdwarf-4` inplace of `-g` (force DWARFv4) to clang everything works as expected.
(I only ever tested with clang-14 on Linux, not sure if this affects other platforms/compilers but I expect it does)

The specifics of the error in symbolicator were 'UnexpectedEof' with corrupt DWARF info. This would show on the logs as 'failed to write symcaches' and in the UI as 'the required debug info was broken'.

For now, using `-gdwarf-4` is an okay workaround, but in the future it'd be great if DWARFv5 was natively supported or at least diagnosed with a better error message.

Thanks!

**Comment by Swatinem** [comment]
Thanks for reporting this.
In theory we should process DWARF5 just fine. Though the `UnexpectedEof` error you mention is something we have to specifically investigate.
Do you have an example file that exhibits this problem that you are willing to share with us? If the file has been uploaded to sentry you can also link to the sentry event that says "the required debug info was broken" and we can download the file from there to inspect it.
