### ISSUE TITLE
azure support for SourceConfig

### ISSUE THREAD

**Issue by wangjiejacques** [getsentry/symbolicator#859]
For now, symbolicator supports S3, Google cloud storage for source, it would be nice if it can also support [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/#overview)
```rust
pub enum SourceConfig {
    /// Sentry debug files endpoint.
    Sentry(Arc<SentrySourceConfig>),
    /// Http server implementing the Microsoft Symbol Server protocol.
    Http(Arc<HttpSourceConfig>),
    /// Amazon S3 bucket containing symbols in a directory hierarchy.
    S3(Arc<S3SourceConfig>),
    /// A google cloud storage bucket.
    Gcs(Arc<GcsSourceConfig>),
    /// Local file system.
    Filesystem(Arc<FilesystemSourceConfig>),
}
```

**Comment by wangjiejacques** [comment]
Hi @Swatinem, do you think it's a good idea to support [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/#overview)?

**Comment by Swatinem** [comment]
I think this is a very good idea.

This is not a high priority for our team though (as we are not using/testing this). We are very open to contributions though, so feel free to give this a shot.
