### ISSUE TITLE
Error while downloading file: download was cancelled

### ISSUE THREAD

**Issue by pigletfly** [getsentry/symbolicator#875]
### Environment

What version are you running? Etc.
self-hosted sentry 22.7.0
symbolicator v0.4.0

### Steps to Reproduce

upload pdb with sentry-cli to self-hosted senty
Run app and execute crash
Go to sentry issues and see

![origin_img_v2_f4bc1281-f69c-455a-a667-7a1a1c93169g](https://user-images.githubusercontent.com/877790/189340662-38ba66a3-7078-4ee8-8c27-6f06bb5e43a4.jpg)

and there is a error in symbolicator

```
2022-09-09T10:08:56Z [symbolicator::services::objects::data_cache] ERROR: Error while downloading file: download was cancelled
```

### Expected Result

What you thought would happen.

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by flub** [comment]
The error message should also show up if you hover of the `missing` pill IIRC.  There might be an issue with the connection between symbolicator and sentry.  You could check the network traffic between them to see what is going on.  You can also enable debug logging on symbolicator (and sentry) to figure out more.  Finally if symbolicator is reporting errors to sentry itself you might find a more descriptive error reporting there as well.

**Comment by pigletfly** [comment]
I am using a self-hosted sentry, and sentry is installed by docker-compose, sentry and symbolicator are running on the same host as a docker container.There shouldn't be any network problem.

**Comment by pigletfly** [comment]
I open the image detail, there is a tooltip says "this issue was processed before this debug information file was available".

**Comment by flub** [comment]
> I open the image detail, there is a tooltip says "this issue was processed before this debug information file was available".

Symbolicator caches negative or missing Debug Information Files (DIFs) results for up to 1h.  So if this was the case you'll have to either clear symbolicator caches completely and restart it or wait for an hour before trying to ingest the issue again.

**Comment by pigletfly** [comment]
> > I open the image detail, there is a tooltip says "this issue was processed before this debug information file was available".
> 
> Symbolicator caches negative or missing Debug Information Files (DIFs) results for up to 1h. So if this was the case you'll have to either clear symbolicator caches completely and restart it or wait for an hour before trying to ingest the issue again.

How do I clear symbolicator cache ?

**Comment by flub** [comment]
- shut it down
- `rm -rf /path/to/configured/cache/dir`

**Comment by Swatinem** [comment]
Symbolicator by now should give better error messages related to download timeouts.
Please reopen if there is still an issue with symbolicator itself (vs timeouts that happen because of slow downloads?)
