### ISSUE TITLE
Clean up internal Error / Cache propagation

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolicator#922]
Our internal error propagation and caching is overly complex and hard to understand.

There are also bugs that cause some statuses not being correctly propagated to the user as was exposed by https://github.com/getsentry/symbolicator/pull/917.

# Problem Statement

The way this is being exposed to users is also duplicated, inconsistent and confusing. There are 4 places these things are exposed currently:

* `frame.status`: Not entirely sure how this is exposed to users?
* `module.debug_status`: This is the main status being exposed to users, visible in the "Loaded Images" list.
* `candidate.debug.status`: Visible in the debug image details, when it is being used for symcaches.
* `candidate.download.status`: Visible in the debug image details.

Currently, download failures due to timeouts or credentials are not being correctly exposed in the "Loaded Images" list, which should be fixed so that users have insight into "failed to fetch" images.

The candidates list might also be missing some candidates in some circumstances.

# Proposal

We did a bit of brainstorming and experimentation. We would like to expose the following statuses across candidates and status details:

```rust
enum CacheEntry<T> {
    AllGood(T), // => symcache => SymCache, object_meta => ObjectFeatures, cficache => SymbolFile
    NotFound,
    PermissionDenied(String), // => whatever the server returned
    Timeout(Duration), // => should we return the duration after which we timed out?
    DownloadError(String), // => connection lost, dns resolution, or 5xx server errors
    Malformed(String), // => unsupported object file, symcache conversion failure
    InternalError, // => unexpected errors like: io::Error, serde_error, symcache parse error,
}
```

To help with cache invalidation, retries and in-memory caching, we also want to internally track a TTL at which the cache needs to be re-tried from its source:

```rust
struct InternalCacheEntry<T> {
    entry: CacheEntry<T>,
    ttl: Instant,
}
```

Last but not least, converting files could be as easy as a `.map` method on the `CacheEntry`.

The base filesystem cache and source downloader would yield a `AllGood(ByteView<'static>)` which is a mmap-ed view to the on-disk file.

This would then be mapped to a `ObjectFeatures` by parsing it as JSON; or a `SymbolFile` by parsing it as a CFI file; etc.

The main entry points to the different cache files would yield such a `CacheEntry` plus a list of candidates:

```
fetch_sources(...) -> (CacheEntry<SourceBundle>, Candidates)
fetch_symcache(...) -> (CacheEntry<SymCache>, Candidates)
...
```

# Implementation Path

Implementing this might be quite a bit of effort.

First step could be to de/serialize at least the error cases into/from files on disks, and make it possible to convert to/from the current `CacheStatus`, with backwards compatibility to the current markers that are written into files.

Refactoring the `DownloadService` to yield such a new status instead of the needlessly detailed / convoluted `DownloadError` would be the next step and would also simplify that service.

Next step would be to somehow hook this up to the `data_cache` and `meta_cache`, which are the next indirection after the pure downloaders.

A simpler usecase still would be the il2cpp / bcsymbolmap services, which are built on downloads directly, and are currently not being exposed in the candidate list at all.

**Comment by Swatinem** [comment]
I will reopen this, as there is still a ton more to do :-)

**Comment by loewenheim** [comment]
Oops, and thank you!

**Comment by Swatinem** [comment]
https://github.com/getsentry/symbolicator/pull/953 and https://github.com/getsentry/symbolicator/pull/956 are going another big step here, though the on-disk format is still using a "legacy" format for the errors.

**Comment by Swatinem** [comment]
Closing this.
We have successfully cleaned up our error propagation :tada:, and more caching work in tracked in #983 and #994
