### ISSUE TITLE
No response after downloading wasm-split

### ISSUE THREAD

**Issue by NuoHui** [getsentry/symbolicator#925]
### Environment

centos x86_64

What version are you running? Etc.

[0.6.0](https://github.com/getsentry/symbolicator/releases/tag/0.6.0)

### Steps to Reproduce

Follow the steps

```
curl -O https://github.com/getsentry/symbolicator/releases/download/0.6.0/wasm-split-Linux-x86_64
chmod +x ./wasm-split-Linux-x86_64
./wasm-split-Linux-x86_64 --help
```
### Expected Result

Show wasm-split 0.6.0 help prompt

### Actual Result
```
sh-4.4# ./wasm-split-Linux-x86_64 --help
sh-4.4# 
```
no error、no response

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by loewenheim** [comment]
As per [this stackoverflow post](https://stackoverflow.com/questions/46060010/download-github-release-with-curl), you have to call `curl -L` to follow the redirect link.

**Comment by NuoHui** [comment]
> As per [this stackoverflow post](https://stackoverflow.com/questions/46060010/download-github-release-with-curl), you have to call `curl` with `-L` to follow the redirect link.

https://github.com/getsentry/symbolicator/issues/925#issuecomment-1332015313

**Comment by NuoHui** [comment]
> As per [this stackoverflow post](https://stackoverflow.com/questions/46060010/download-github-release-with-curl), you have to call `curl` with `-L` to follow the redirect link.

I want to know how to use wasm split in centos. I can do it under mac, but the same operation can’t work in centos

**Comment by ashwoods** [comment]
Tested in centos with docker, works the same as in mac. Double check if the downloaded binary is correct:

```
docker run -it centos:latest /bin/bash

$ curl -LO https://github.com/getsentry/symbolicator/releases/download/0.6.0/wasm-split-Linux-x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1146k  100 1146k    0     0  1205k      0 --:--:-- --:--:-- --:--:-- 11.5M
$ md5sum wasm-split-Linux-x86_64 
fbf87be150f935e0db0aecb09b04788f  wasm-split-Linux-x86_64

$ chmod +x wasm-split-Linux-x86_64 
$ ./wasm-split-Linux-x86_64 --help

wasm-split 0.6.0
Adds build IDs to wasm files.

This tool can both add missing build IDs and split a WASM file into two: a main binary and a debug companion file.  The
debug companion file will contain all sections of the original file. This is necessary as DWARF processing requires
knowing the location of all sections (specially the code section) to calculate offsets.

This prints the embedded build_id in hexadecimal format to stdout.

USAGE:
    wasm-split-Linux-x86_64 [FLAGS] [OPTIONS] <input>
...
```
