### ISSUE TITLE
Could not recognise discriminant 0xD for type Section

### ISSUE THREAD

**Issue by matusfedorko** [getsentry/symbolicator#969]
Hi,
this is more of a question rather than a bug report. I am trying to use `wasm-split`, but I get the following error:

```
Error: (root)[4]: Could not recognise discriminant 0xD for type Section

Caused by:
    Could not recognise discriminant 0xD for type Section
```

This is how I invoke `wasm-split`: `./wasm-split-Windows-x86_64.exe main.wasm`

I have no idea what the above error means. The executable should be fine as far as I am concerned.

**Comment by matusfedorko** [comment]
All right, I found something here: [https://github.com/GoogleChromeLabs/wasmbin/issues/7](https://github.com/GoogleChromeLabs/wasmbin/issues/7) The same issue, that I ran into. We are also enabling exceptions in our builds (`-fwasm-exceptions`). Sadly the pull request for that feature is still open.

**Comment by Swatinem** [comment]
@matusfedorko thanks for reporting this and tracking it down to one of our dependencies, and thanks as well for engaging with the upstream developers :-)

That being said, we would need to wait for an updated dependency before we can incorporate the fix on our end.

**Comment by Swatinem** [comment]
https://github.com/getsentry/symbolicator/pull/1081 updated `wasmbin` to `0.5.0` which I believe should include a fix for this. We don’t have a fixed release schedule for symbolicator and its tools, so if its urgent feel free to reach out.

**Comment by Swatinem** [comment]
Sorry for the delay. Can you share your wasm file in any way? Though as this is clearly a problem with one of our dependencies, I’m not sure how quickly we can work around that on our end.

**Comment by mcdurdin** [comment]
I'm running into this same issue; attaching a sample [wasm-host.zip](https://github.com/getsentry/symbolicator/files/12035870/wasm-host.zip) file (emerging from work in  keymanapp/keyman#9243). Command that I ran:

```
$ wasm-split wasm-host.wasm -o kmcmplib.wasm --strip --debug-out=kmcmplib.debug.wasm

Error: (root):<ModuleRepr>.sections[5]: Could not recognise discriminant 0xD for type wasmbin::sections::Section

Caused by:
    Could not recognise discriminant 0xD for type wasmbin::sections::Section

$ wasm-split -V
wasm-split 23.6.2
```

(Note: wasm-split-Windows-x86_64.exe, aliased to wasm-split)

**Comment by mcdurdin** [comment]
Note: this is still an issue, just tried latest wasm-split 24.3.0 and received the same error, with example from my previous comment.

**Comment by Swatinem** [comment]
I just updated the `wasmbin` dependency yesterday, there hasn’t been any automated release yet.
